[package]
name = "greeting_client"
version = "0.1.0"
edition = "2018"

[dependencies]
async-trait = "0.1"
paste = "1.0"
reqwest = { version = "0.11", features = ["json"] }
serde = { version = "1", features = ["derive"] }
warp_rpc = { git = "https://github.com/kouky/warp_rpc" }

